senior_data_analyst_task:
  description: >
    Retrieve cryptocurrency data based on the user's specified ticker and timeframe (default: BTC, 1 year). The data should include:
    1) Cryptocurrency Name & Ticker
    2) Market Capitalization
    3) Circulating Supply
    4) Historical Price Metrics (Average, Maximum, Minimum)
    If no ticker or timeframe is provided, request clarification or use defaults. 
    Present the data in a clear, structured, user-friendly format.

    User crypto: {ticker}.
    User period: {period}.
  expected_output: >
    A structured summary of the cryptocurrency's financial metrics and historical price performance.


news_researcher_task:
  description: >
    1. Search for recent and relevant information about the cryptocurrency specified by the user.
    2. Use reliable sources such as news websites, blogs, or cryptocurrency forums to provide up-to-date insights.
    3. If the user doesn't provide a cryptocurrency ticker, request clarification.

    User crypto: {ticker}.

    Your response should include:
    - A concise summary of recent news related to the cryptocurrency.
    - Key developments, trends, or events that may impact the cryptocurrency's market or reputation.
  expected_output: >
    A structured summary of relevant news and insights about the specified cryptocurrency.


fundamental_analyst_task:
  description: >
    1. Analyze the cryptocurrency's project whitepaper to assess its long-term vision and goals.
    2. Evaluate the team and advisors behind the cryptocurrency project, including their experience and reputation.
    3. Investigate any partnerships or collaborations that the project has secured to evaluate its credibility and growth potential.
    4. Provide a comprehensive summary of the project's fundamental strengths and weaknesses based on the above factors.
  
    User crypto: {ticker}.
  expected_output: >
    A structured analysis of the project's whitepaper, roadmap, team, advisors, and partnerships. 
    This analysis should focus on the project's long-term potential, credibility, and growth opportunities.


technical_analyst_task:
  description: >
    1. Retrieve historical price data for the given cryptocurrency over the specified period.
    2. Calculate key technical indicators, including the 50-day SMA and 200-day SMA, to analyze market trends.
    3. Assess potential bullish or bearish trends based on SMA crossovers and price movements.
    4. Provide a comprehensive summary of the cryptocurrency's technical outlook based on the above factors.
  
    User crypto: {ticker} 
    Period: {period}
  expected_output: >
    A structured technical analysis of the cryptocurrency, including calculated SMA values, trend analysis, 
    and potential trading signals. The analysis should help users understand market momentum and price trends 
    for informed decision-making.


financial_analyst_task:
  description: >
    1. Integrate insights from both fundamental and technical analysis to assess the cryptocurrency's overall financial health.
    2. Evaluate key financial metrics such as market capitalization, trading volume, liquidity, volatility, and risk-reward ratios.
    3. Identify potential investment strategies based on historical performance, market conditions, and investor risk tolerance.
    4. Provide a structured recommendation on whether to invest, hold, or avoid the cryptocurrency, along with risk mitigation strategies.

    User crypto: {ticker}
    Period: {period}
  expected_output: >
    A structured financial analysis that combines fundamental and technical insights to evaluate the cryptocurrency's 
    investment potential. This includes risk-reward assessment, liquidity analysis, volatility evaluation, and 
    suggested investment strategies tailored to market conditions.


technical_report_task:
  description: >
    1. Use the output from the Data Collector Agent to include detailed data metrics about the cryptocurrency 
       in a tabular format.
    2. Use the output from the Crypto Researcher Agent to summarize key news, events, or trends about the cryptocurrency.
    3. Use the output from the Fundamental Analysis Agent to include an evaluation of the cryptocurrency's whitepaper, 
       team, roadmap, and partnerships, providing insights into the project's long-term potential.
    4. Use the output from the Technical Analysis Agent to assess key technical indicators such as the 50-day SMA and 
       200-day SMA, analyzing price trends and market momentum.
    5. Evaluate market sentiment based on technical indicators, providing insights into potential bullish or bearish trends.
    6. Organize the report into the following structure:
       - Introduction: Brief overview of the cryptocurrency, its history, and its relevance in the market.
       - Cryptocurrency Metrics: Present the collected data in a table format (e.g., price, market cap, circulating supply, etc.).
       - Information Summary: Summarize the retrieved research, including key developments, trends, and news.
       - Fundamental Analysis: Provide a detailed analysis of the project's whitepaper, team, roadmap, and partnerships.
       - Technical Analysis: Present key indicators such as the 50-day SMA, 200-day SMA, MACD, RSI, and their implications.
       - Sentiment Analysis: Assess market sentiment based on technical indicators and price trends, highlighting bullish or bearish signals.
       - Conclusion: Provide an overall assessment, including investment strategies and potential risks.
  expected_output: >
    A well-structured cryptocurrency report with the following sections:
    - Introduction: A brief overview of the cryptocurrency, including its background and relevance.
    - Cryptocurrency Metrics: Data metrics presented in a table format (e.g., price, market cap, historical trends).
    - Information Summary: Concise research summary, highlighting trends, news, and key events.
    - Fundamental Analysis: A detailed analysis covering the whitepaper, team, roadmap, and partnerships.
    - Technical Analysis: Summary of key technical indicators (50-day SMA, 200-day SMA, MACD, RSI) and their market implications.
    - Sentiment Analysis: Market sentiment evaluation based on technical trends, highlighting bullish or bearish signals.
    - Conclusion: Overall assessment with investment strategies, risks, and potential recommendations.


