data_collector_task:
  description: >
    1. Retrieve cryptocurrency data based on the user crytocurrency, including its name, ticker, market cap, circulating supply, 
       and historical stock price metrics (average, maximum, and minimum) over the specified timeframe.
    2. If no ticker or timeframe is mentioned, request clarification from the user or use default values 
       (e.g., BTC for ticker and 1 year for timeframe).
    3. Provide a summary of the collected data in a clear, user-friendly format.

    User crypto: {ticker}.
    User period: {period}.

    Your response should include:
    - Cryptocurrency Name and Ticker
    - Market Cap
    - Circulating Supply
    - Stock Price Average, Maximum, and Minimum over the specified period
  expected_output: >
    A structured summary of the cryptocurrency's financial metrics and historical price performance.


crypto_researcher_task:
  description: >
    1. Search for recent and relevant information about the cryptocurrency specified by the user.
    2. Use reliable sources such as news websites, blogs, or cryptocurrency forums to provide up-to-date insights.
    3. If the user doesn't provide a cryptocurrency ticker, request clarification.

    User crypto: {ticker}.

    Your response should include:
    - A concise summary of recent news related to the cryptocurrency.
    - Key developments, trends, or events that may impact the cryptocurrency's market or reputation.
  expected_output: >
    A structured summary of relevant news and insights about the specified cryptocurrency.


fundamental_analysis_task:
  description: >
    1. Analyze the cryptocurrency's project whitepaper to assess its long-term vision and goals.
    2. Evaluate the team and advisors behind the cryptocurrency project, including their experience and reputation.
    3. Investigate any partnerships or collaborations that the project has secured to evaluate its credibility and growth potential.
    4. Provide a comprehensive summary of the project's fundamental strengths and weaknesses based on the above factors.
  
    User crypto: {ticker}.
  expected_output: >
    A structured analysis of the project's whitepaper, roadmap, team, advisors, and partnerships. 
    This analysis should focus on the project's long-term potential, credibility, and growth opportunities.


reporting_task:
  description: >
    1. Use the output from the Data Collector Agent to include detailed data metrics about the cryptocurrency 
       in a tabular format.
    2. Use the output from the Crypto Researcher Agent to summarize key news, events, or trends about the cryptocurrency.
    3. Use the output from the Fundamental Analysis Agent to include an evaluation of the cryptocurrency’s whitepaper, 
       team, roadmap, and partnerships, providing insights into the project's long-term potential.
    4. Organize the report into the following structure:
       - Introduction: Brief overview of the cryptocurrency, its history, and its relevance in the market.
       - Cryptocurrency Metrics: Present the collected data in a table format (e.g., price, market cap, circulating supply, etc.).
       - Information Summary: Summarize the retrieved research, including key developments, trends, and news.
       - Fundamental Analysis: Provide a detailed analysis of the project's whitepaper, team, roadmap, and partnerships.
       - Conclusion: Provide an overall assessment, including investment strategies and potential risks.
  expected_output: >
    A well-structured cryptocurrency report with the following sections:
    - Introduction: A brief overview of the cryptocurrency, including its background and relevance.
    - Cryptocurrency Metrics: Data metrics presented in a table format (e.g., price, market cap, historical trends).
    - Information Summary: Concise research summary, highlighting trends, news, and key events.
    - Fundamental Analysis: A detailed analysis covering the whitepaper, team, roadmap, and partnerships.
    - Conclusion: Overall assessment with investment strategies, risks, and potential recommendations.

