data_collector_task:
  description: >
    1. Retrieve cryptocurrency data based on the user crytocurrency, including its name, ticker, market cap, circulating supply, 
       and historical stock price metrics (average, maximum, and minimum) over the specified timeframe.
    2. If no ticker or timeframe is mentioned, request clarification from the user or use default values 
       (e.g., BTC for ticker and 1 year for timeframe).
    3. Provide a summary of the collected data in a clear, user-friendly format.

    User crypto: {ticker}.
    User period: {period}.

    Your response should include:
    - Cryptocurrency Name and Ticker
    - Market Cap
    - Circulating Supply
    - Stock Price Average, Maximum, and Minimum over the specified period
  expected_output: >
    A structured summary of the cryptocurrency's financial metrics and historical price performance.


crypto_researcher_task:
  description: >
    1. Search for recent and relevant information about the cryptocurrency specified by the user.
    2. Use reliable sources such as news websites, blogs, or cryptocurrency forums to provide up-to-date insights.
    3. If the user doesn't provide a cryptocurrency ticker, request clarification.

    User crypto: {ticker}.

    Your response should include:
    - A concise summary of recent news related to the cryptocurrency.
    - Key developments, trends, or events that may impact the cryptocurrency's market or reputation.
  expected_output: >
    A structured summary of relevant news and insights about the specified cryptocurrency.


reporting_task:
  description: >
    1. Use the output from the Data Collector Agent to include detailed data metrics about the cryptocurrency 
       in a tabular format.
    2. Use the output from the Crypto Researcher Agent to summarize key news, events, or trends about the cryptocurrency.
    3. Organize the report into the following structure:
       - Introduction: Brief overview of the cryptocurrency and its relevance.
       - Cryptocurrency Metrics: Present the collected data in a table format.
       - Information Summary: Summarize the retrieved research in a clear, concise manner.
       - Conclusion: Provide an overall assessment and offer investment strategies.
  expected_output: >
    A well-structured cryptocurrency report with the following sections:
    - Introduction
    - Data Metrics (in a tabular format)
    - Information Summary
    - Conclusion with investment strategies
